databases:
  - name: CollectorSwap
    databaseName: collector_swap
    user: collector_swap

services:
  - type: web
    name: collector_swap
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://db_collectorswap:qT3h4t9RMLrSAEvWW6tysGBYiv5plbxz@dpg-clc29al4lnec73e0dv7g-a/db_collectorswap
        fromDatabase:
          name: mysite
          property: connectionString
      - key: e5c5c0fd21619c12201deace270e9333
        sync: false