development: 
  cloud_name: <%= ENV["CL_USER"] %>
  api_key: <%= ENV["CL_KEY"] %>
  api_secret: <%= ENV["CL_PASSWORD"] %>
  secure: true

production:
  cloud_name: <%= ENV["CL_USER"] %>
  api_key: <%= ENV["CL_KEY"] %>
  api_secret: <%= ENV["CL_PASSWORD"] %>
  secure: true